project_id = "siafgzfpzowztfhlajtn"

[functions.scrape-instagram]
verify_jwt = false

[functions.image-proxy]
verify_jwt = false

[functions.generate-script]
verify_jwt = true

[functions.tiktok-oembed]
verify_jwt = false

[functions.get-or-scrape-search]
verify_jwt = true

[functions.enhanced-script-generation]
verify_jwt = true

[functions.scrape-tiktok-user]
verify_jwt = true

[functions.search-instagram-creators]
verify_jwt = true

[functions.analyze-content]
verify_jwt = true

[functions.assemblyai-webhook]
verify_jwt = false