project_id = "siafgzfpzowztfhlajtn"

[functions.process-profile-videos]
verify_jwt = true

[functions.test-apify-access]
verify_jwt = false

[functions.scrape-instagram]
verify_jwt = false

[functions.image-proxy]
verify_jwt = false

[functions.generate-script]
verify_jwt = true

[functions.tiktok-oembed]
verify_jwt = false

[functions.get-or-scrape-search]
verify_jwt = true

[functions.enhanced-script-generation]
verify_jwt = true

[functions.scrape-tiktok-user]
verify_jwt = true

[functions.search-instagram-creators]
verify_jwt = true

[functions.analyze-content]
verify_jwt = true

[functions.assemblyai-webhook]
verify_jwt = false

[functions.extract-instagram-video]
verify_jwt = true

[functions.extract-tiktok-video]
verify_jwt = true

[functions.recover-stuck-analyses]
verify_jwt = true

[functions.scrape-instagram-hashtags]
verify_jwt = true

[functions.scrape-tiktok-hashtags]
verify_jwt = true

[functions.search-tiktok-creators]
verify_jwt = true