project_id = "siafgzfpzowztfhlajtn"

[functions.scrape-instagram]
verify_jwt = false

[functions.image-proxy]
verify_jwt = false

[functions.generate-script]
verify_jwt = true

[functions.tiktok-oembed]
verify_jwt = false